def test_register_user(page):
    print("Running Test case 1 - Register User")
    page.goto("https://automationexercise.com/")
    assert page.title() == "Automation Exercise"
    page.click("a[href='/login']")
    signup_header = page.locator("text=New User Signup!")
    assert signup_header.is_visible()
    page.fill("input[placeholder='Name']", "S25")
    page.fill("input[data-qa='signup-email']", "s25@samsung.com")
    page.click("button[data-qa='signup-button']")
    assert page.locator("text=Enter Account Information").is_visible()
    page.click("#id_gender1")
    page.fill("#password", "password123")
    page.select_option("#days", "1")
    page.select_option("#months", "1")
    page.select_option("#years", "2000")
    page.click("#newsletter")
    page.click("#optin")
    page.fill("#first_name", "Lulu")
    page.fill("#last_name", "Lemon")
    page.fill("#address1", "New York")
    page.select_option("#country", "United States")
    page.fill("#state", "New York")
    page.fill("#city", "New York")
    page.fill("#zipcode", "123456")
    page.fill("#mobile_number", "0987654321")
    page.click("button[data-qa='create-account']")
    assert page.locator("text=Account Created!").is_visible()
    page.click(".btn.btn-primary")
    assert page.locator("text=Logged in as S25").is_visible()
    page.click("a[href='/delete_account']")
    assert page.locator("text=Account Deleted!").is_visible()
    print("Test Passed: User registration successfull. \n")



